### ISSUE TITLE
i found it! i love it!

### ISSUE THREAD

**Issue by linus0902** [pedrolcl/wrk2mid#1]
i love it so much! thx! but the output midi files lost all the markers and other midiports (i have 3 ports) ,all ports became "1-ports".
plz tell me how can i do it that keep all of the markers and Midiports.

thanks again.

**Comment by pedrolcl** [comment]
Hi! Thank you very much!

**Comment by pedrolcl** [comment]
# About the MIDI ports 

The **Drumstick::File** signal `signalWRKTrack2()` has a number of parameters, and one of them is the port. See the documentation of this signal here:
https://drumstick.sourceforge.io/docs/classdrumstick_1_1File_1_1QWrk.html#a5d5cbc6fe3813b626d15789f70a47131

When this signal is processed, here: https://github.com/pedrolcl/wrk2mid/blob/master/sequence.cpp#L473
the parameters: port, selected, muted, and loop are ignored. Only the track name is used. You need to do something here with the port parameter. The problem is that SMF tracks don't have this property. There was a "forced port" meta event, which the standard says now that is deprecated, in favor of the new Device Name and Program Name Meta Events:

https://www.midi.org/specifications/file-format-specifications/standard-midi-files/smf-device-name-and-program-name-meta-events

All the SMF documentation is here: https://www.midi.org/specifications/file-format-specifications/standard-midi-files

**Comment by pedrolcl** [comment]
This is an excerpt  of the SMF spec:

##  MIDI Channel Prefix

FF 20 01 cc 

The MIDI channel (0-15) contained in this event may be used to associate a MIDI channel with all events which follow, including System Exclusive and meta-events. This channel is "effective" until the next normal MIDI event (which contains a channel) or the next MIDI Channel Prefix meta-event. If MIDI channels refer to "tracks", this message may help jam several tracks into a format 0 file, keeping their non-MIDI data associated with a track. This capability is also present in Yamaha's ESEQ file format.

There was another Meta Event: FF 21 01 cc  (MIDI Port Prefix) which was used for the same purpose as the corresponding Cakewalk track parameter, but you may find that your current sequencer does not understand it.

**Comment by pedrolcl** [comment]
# About the markers: 

This is the opposite case of the port number. There are perfectly defined SMF meta events for text markers and cue points, but I don't know about how Cakewalk stores markers. So the first step should be locate, document and implement in Drumstick signals for them. It would help to have some files with these types of events.

## Marker

FF 06 length text

This optional event is used to label points within a sequence, e.g. rehearsal letters, loop points, or section names (such as 'First verse').

For a format 1 MIDI file, Marker Meta events should only occur within the first MTrk chunk.

## Cue Point

FF 07 length text

This optional event is used to describe something that happens within a film, video or stage production at that point in the musical score. E.g. 'Car crashes', 'Door opens', etc.

For a format 1 MIDI file, Cue Point Meta events should only occur within the first MTrk chunk.

**Comment by pedrolcl** [comment]
Tickets created in Sourceforge, at Drumstick (https://sourceforge.net/p/drumstick/bugs/37/) and wrk2mid (https://sourceforge.net/p/wrk2mid/tickets/).

**Comment by pedrolcl** [comment]
Just in case you are listening: you should check the `devel` branch of wrk2mid with current drumstick, to see your marks and ports.

**Comment by pedrolcl** [comment]
solved in v1.1.0
